#!/usr/bin/env python3

from rich.text import Text
from rich.live import Live
import asyncio
import sys

async def main():
    message = ' '.join(sys.argv[1:])
    with Live(Text(""), auto_refresh=False) as live:
        for i in range(0, len(message), 5):
            live.update(Text(message[:i]))
            live.refresh()
            await asyncio.sleep(0.05)

        live.update(Text(message))
        live.refresh()

asyncio.run(main())

