#!/bin/bash

b -c "I'm looking for the \"$@\" emoji. Please output emojis in the following format: \`🌼\` - \`🏤\` - \`🐯\` - \`🌃\` - \`🌷\` - \`🕰️\` - \`✌️\` - \`💯\` (Include the backquotes, they make it easier to copy.) Please return the best available emojis matching my query: \"$@\"."
