#!/bin/bash

b "Please return emojis matching this query: \"" $@ "\". Please use the following format: \`🌼\` - \`🌸\` - \`💐\` - \`🌷\` - \`🌹\` - \`🏵️\`. (Include the backticks, they make it easier to copy.)"
