#!/bin/bash

function fail() {
    BYLW="\033[93m"
    echo -e "${BYLW}Brerun aborted or no editor configured"
    exit 1
}

# Open the user's configured editor and save the input to a temporary file
tempfile=$(mktemp)
b --show=user > $tempfile
$EDITOR $tempfile || fail

# Pipe the contents of the temporary file to another shell script
# Include my arguments
cat $tempfile | b $@

# Remove the temporary file
rm $tempfile

